{
 "title": "New dashboard",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   { "name": "datasource0", "label": "Datasource", "query": "prometheus" },
   { "name": "adhoc0", "label": "Ad-Hoc Filter" }
  ]
 },
 "panels": [
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Query Duration (Seconds)",
   "type": "bargauge",
   "description": "Groups the query durations for each resolve attempt into buckets containing the number of results in this bucket. The values are a \"rate\" which is calculated on every refresh for the prospected time interval.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (rate(syringe_query_response_time_bucket[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Query Response Ttl (Seconds)",
   "type": "bargauge",
   "description": "Groups the query response ttl for each resolve attempt into buckets containing the number of results in this bucket. The values are a \"rate\" which is calculated on every refresh for the prospected time interval.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (rate(syringe_query_response_ttl_bucket[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Resolve Rate by Strategy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(strategy) (rate(domains_resolved_by_strategy[$__rate_interval]))",
     "legendFormat": "{{strategy}}"
    }
   ]
  },
  {
   "title": "QPS by Instance",
   "type": "timeseries",
   "description": "Issued queries (rate) grouped by resolver instance",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(syringe_query_response_time_count[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Domains resolved total",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(domains_resolved_by_strategy)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Queue size (avg)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(sum(syringe_queue_size))", "legendFormat": "total" }
   ]
  },
  {
   "title": "Queue candidates (Seconds until due)",
   "type": "bargauge",
   "description": "Groups the scheduled queries for each resolve attempt into buckets containing the number of results in this bucket. The values are a \"rate\" which is calculated on every refresh for the prospected time interval.",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (rate(syringe_queue_candidate_timer_bucket[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Debug Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Threads/GoRoutines by Instance (avg)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "targets": [
    { "expr": "sum by(instance) (go_threads)", "legendFormat": "Threads {{instance}}" },
    {
     "expr": "avg by(instance) (sum by(instance) (go_goroutines))",
     "legendFormat": "GoRoutines {{instance}}"
    }
   ]
  },
  {
   "title": "Go Version",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "targets": [
    { "expr": "go_info", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "Memory Usage by Instance (avg)",
   "type": "timeseries",
   "description": "Average memory usage grouped by resolver instance",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(sum by(instance) (go_memstats_alloc_bytes))",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}