// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://github.com/TCMPK/syringe",
        "contact": {
            "name": "Peter Klein",
            "url": "https://blog.tcmpk.de",
            "email": "github@tcmpk.de"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/domains": {
            "get": {
                "description": "Responds with the queue",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "syringe"
                ],
                "summary": "Return a list of domains currently in the queue",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.ResponseWithDomains"
                        }
                    }
                }
            },
            "post": {
                "description": "Responds with the new queue size",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "syringe"
                ],
                "summary": "Load domains into the queue",
                "parameters": [
                    {
                        "description": "domain list",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.DomainListDefinition"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.ResponseWithSize"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.Response"
                        }
                    }
                }
            }
        },
        "/domains/count": {
            "get": {
                "description": "Responds with the queue size",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "syringe"
                ],
                "summary": "Return the number of domains in the queue",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.ResponseWithSize"
                        }
                    }
                }
            }
        },
        "/domains/random": {
            "post": {
                "description": "Responds with the new queue size",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "syringe"
                ],
                "summary": "Load random domains from the configured domains file",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "example": 10,
                        "description": "int valid",
                        "name": "count",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.ResponseWithSize"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.DomainDefinition": {
            "type": "object",
            "properties": {
                "domain": {
                    "type": "string",
                    "example": "google.com"
                },
                "type": {
                    "type": "string",
                    "example": "A"
                }
            }
        },
        "main.DomainListDefinition": {
            "type": "object",
            "properties": {
                "domains": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.DomainDefinition"
                    }
                }
            }
        },
        "main.Response": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "main.ResponseWithDomains": {
            "type": "object",
            "properties": {
                "domains": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.DomainDefinition"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "main.ResponseWithSize": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "success"
                },
                "size": {
                    "type": "integer",
                    "example": 1
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Syringe Api Documentation",
	Description:      "A lightweight api for the syringe daemon",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
