name: Docker Image CI

on:
  push:
    tags:
    - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}

    - name: Set Versions
      uses: actions/github-script@v6
      id: set_version
      with:
        result-encoding: string
        script: |
          const tag = context.ref.substring(10)
          const no_v = tag.replace('v', '')
          return no_v

    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ${{secrets.DOCKERHUB_USERNAME}}/syringe:latest
          ${{secrets.DOCKERHUB_USERNAME}}/syringe:${{steps.set_version.outputs.result}}
    - name: Sync README.md to DockerHub
      uses: ms-jpq/sync-dockerhub-readme@v1
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password:  ${{secrets.DOCKERHUB_TOKEN}}
        repository: tcmpk/syringe
        readme: "./README.md"